# SPDX-FileCopyrightText: 2023 bootloose authors
# SPDX-License-Identifier: Apache-2.0

name: Publish Image

on:
  workflow_call:
    inputs:
      image:
        type: string
        description: The image to be published.
      tag:
        type: string
        description: The tag to use for the image. Defaults to :latest if not specified.
        required: false
        default: latest
    secrets:
      QUAY_USERNAME:
        description: The username used to log in to Quay.io.
        required: true
      QUAY_PASSWORD:
        description: The password used to log in to Quay.io.
        required: true

  workflow_dispatch:
    inputs:
      image:
        type: string
        description: The image to be published.
      tag:
        type: string
        description: The tag to use for the image. Defaults to :latest if not specified.
        required: false
        default: latest

jobs:
  publish_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: List image platforms
      id: list-platforms
      run: |
        platforms=$(make -s -C images "${{ inputs.image }}-platforms")
        echo "platforms=${platforms}" >> $GITHUB_OUTPUT

    - name: Login to Quay
      uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4.5.0
      with:
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io

    - name: Set up QEMU
      uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      with:
        platforms: ${{ steps.list-platforms.outputs.platforms }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

    - name: Cache Buildx Docker layers
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx

    - name: Build ${{ inputs.image }}
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
      with:
        platforms: ${{ steps.list-platforms.outputs.platforms }}
        push: true
        tags: |
          quay.io/k0sproject/bootloose-${{ inputs.image }}:${{ inputs.tag }}
        context: images/${{ inputs.image }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
