# SPDX-FileCopyrightText: 2023 bootloose authors
# SPDX-License-Identifier: Apache-2.0

name: Publish Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'images/**/Dockerfile'
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to use for images. Defaults to :latest if not specified.'
        required: false
        default: 'latest'

jobs:
  prepare:
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}
      images: ${{ steps.set-images.outputs.images }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Tag from dispatch
      if: github.event_name == 'workflow_dispatch'
      run: echo "tag=${{ github.event.inputs.tag || 'latest' }}" >> $GITHUB_ENV
    
    - name: Tag from ref
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Default tag
      if: github.event_name != 'workflow_dispatch' && !startsWith(github.ref, 'refs/tags/')
      run: echo "tag=latest" >> $GITHUB_ENV

    - name: Set tag
      id: set-tag
      run: echo "tag=${tag}" >> $GITHUB_OUTPUT

    - name: List all images
      if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
      run: |
        image_dirs=$(find images -name 'Dockerfile' -exec dirname {} \; | xargs -n 1 basename | tr '\n' ' ')
        echo "image_dirs=$image_dirs" >> $GITHUB_ENV

    - name: List changed images
      if: github.event_name != 'workflow_dispatch' && !startsWith(github.ref, 'refs/tags/')
      run: |
        image_dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'images/.*/Dockerfile' | awk -F/ '{print $(NF-1)}' | tr '\n' ' ' | sed 's/ $//')
        echo "image_dirs=$image_dirs" >> $GITHUB_ENV

    - name: Set image list
      id: set-images
      run: |
        image_dirs_json=$(echo "$image_dirs" | jq -R -c 'split(" ") | map(select(. != ""))')
        echo "images=${image_dirs_json}}" >> $GITHUB_OUTPUT

  publish_images:
    needs: prepare
    strategy:
      matrix:
        image: ${{fromJson(needs.prepare.outputs.images)}}
      fail-fast: false

    uses: ./.github/workflows/publish-image.yaml
    with:
      image: ${{ matrix.image }}
      tag: ${{ needs.prepare.outputs.tag }}
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
