# SPDX-FileCopyrightText: 2023 bootloose authors
# SPDX-License-Identifier: Apache-2.0

name: Publish Image

on:
  workflow_call:
    inputs:
      image:
        type: string
        description: The image to be published.
      tag:
        type: string
        description: The tag to use for the image. Defaults to :latest if not specified.
        required: false
        default: latest
    secrets:
      QUAY_USERNAME:
        description: The username used to log in to Quay.io.
        required: true
      QUAY_PASSWORD:
        description: The password used to log in to Quay.io.
        required: true

  workflow_dispatch:
    inputs:
      image:
        type: string
        description: The image to be published.
      tag:
        type: string
        description: The tag to use for the image. Defaults to :latest if not specified.
        required: false
        default: latest

jobs:
  publish_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: List image platforms
      id: list-platforms
      run: |
        platforms=$(make -s -C images "${{ inputs.image }}-platforms")
        echo "platforms=${platforms}" >> $GITHUB_OUTPUT

    - name: Login to Quay
      uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
      with:
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io

    - name: Set up QEMU
      uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      with:
        platforms: ${{ steps.list-platforms.outputs.platforms }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

    - name: Cache Buildx Docker layers
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx

    - name: Build ${{ inputs.image }}
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
      with:
        platforms: ${{ steps.list-platforms.outputs.platforms }}
        push: true
        tags: |
          quay.io/k0sproject/bootloose-${{ inputs.image }}:${{ inputs.tag }}
        context: images/${{ inputs.image }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
